# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tinylink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(auto_created=True, verbose_name='Last validation')),
                ('long_url', models.CharField(max_length=2500, verbose_name='Long URL')),
                ('short_url', models.CharField(max_length=32, unique=True, verbose_name='Short URL')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Status')),
                ('validation_error', models.CharField(default=b'', max_length=100, verbose_name='Validation Error')),
                ('amount_of_views', models.PositiveIntegerField(default=0, verbose_name='Amount of views')),
                ('redirect_location', models.CharField(default=b'', max_length=2500, verbose_name='Redirect location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinylinks', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
